import {invert} from "../../utils/object";

export const Key = {
    Back: 'Back',
    Enter: 'Enter',
    Left: 'ArrowLeft',
    Up: 'ArrowUp',
    Right: 'ArrowRight',
    Down: 'ArrowDown',
    Info: 'Info',
    Play: 'MediaPlay',
    Stop: 'MediaStop',
    Pause: 'MediaPause',
    FastForward: 'MediaFastForward',
    Rewind: 'MediaRewind',
    PlayPause: 'MediaPlayPause',
    Number0: '0',
    Number1: '1',
    Number2: '2',
    Number3: '3',
    Number4: '4',
    Number5: '5',
    Number6: '6',
    Number7: '7',
    Number8: '8',
    Number9: '9',
    ChannelUp: 'ChannelUp',
    ChannelDown: 'ChannelDown',
    Red: 'ColorF0Red',
    Green: 'ColorF1Green',
    Yellow: 'ColorF2Yellow',
    Blue: 'ColorF3Blue',
    Mute: 'AudioVolumeMute',
    VolumeUp: 'AudioVolumeUp',
    VolumeDown: 'AudioVolumeDown',
    Menu: 'Menu',
}

export const keyMap = {
    [Key.Enter]: 13,
    [Key.Back]: 8,
    [Key.Info]: 457,
    [Key.Left]: 37,
    [Key.Up]: 38,
    [Key.Right]: 39,
    [Key.Down]: 40,
    [Key.Play]: 415,
    [Key.Stop]: 413,
    [Key.Pause]: 19,
    [Key.FastForward]: 417,
    [Key.Rewind]: 412,
    [Key.Number0]: 48,
    [Key.Number1]: 49,
    [Key.Number2]: 50,
    [Key.Number3]: 51,
    [Key.Number4]: 52,
    [Key.Number5]: 53,
    [Key.Number6]: 54,
    [Key.Number7]: 55,
    [Key.Number8]: 56,
    [Key.Number9]: 57,
    [Key.ChannelUp]: 33,
    [Key.ChannelDown]: 34,
    [Key.Red]: 403,
    [Key.Green]: 404,
    [Key.Yellow]: 405,
    [Key.Blue]: 406,
    [Key.Mute]: undefined,
    [Key.VolumeUp]: undefined,
    [Key.VolumeDown]: undefined,
    [Key.Menu]: undefined,
    [Key.PlayPause]: undefined,
}

export const inverseKeyMap = invert(keyMap)